// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiYnMtXFDJQxd2Ec7ffJe5LEDWOZORYYM',
    appId: '1:851879795668:web:43ddeb1d3bfcc5f5479441',
    messagingSenderId: '851879795668',
    projectId: 'mymusic-2c880e08',
    authDomain: 'mymusic-2c880e08.firebaseapp.com',
    storageBucket: 'mymusic-2c880e08.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxHqqMALftZn18w4To2vWypSg_Bpjvu4g',
    appId: '1:851879795668:android:d7d1dda2d66378b1479441',
    messagingSenderId: '851879795668',
    projectId: 'mymusic-2c880e08',
    storageBucket: 'mymusic-2c880e08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiW8pSXhoSVSO8vluluzw59QN_3PblbM4',
    appId: '1:851879795668:ios:935cd51d983c29ae479441',
    messagingSenderId: '851879795668',
    projectId: 'mymusic-2c880e08',
    storageBucket: 'mymusic-2c880e08.firebasestorage.app',
    iosBundleId: 'com.antigravity.spotifyplayer.musicPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiW8pSXhoSVSO8vluluzw59QN_3PblbM4',
    appId: '1:851879795668:ios:2e17c61114b4615b479441',
    messagingSenderId: '851879795668',
    projectId: 'mymusic-2c880e08',
    storageBucket: 'mymusic-2c880e08.firebasestorage.app',
    iosBundleId: 'com.example.musicPlayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiYnMtXFDJQxd2Ec7ffJe5LEDWOZORYYM',
    appId: '1:851879795668:web:aef5cb168452bb5a479441',
    messagingSenderId: '851879795668',
    projectId: 'mymusic-2c880e08',
    authDomain: 'mymusic-2c880e08.firebaseapp.com',
    storageBucket: 'mymusic-2c880e08.firebasestorage.app',
  );
}
